<<<<<<< Updated upstream
<<<<<<< Updated upstream:apps/post/migrations/0002_auto_20200911_1405.py
<<<<<<< Updated upstream
=======
<<<<<<< Updated upstream:apps/post/migrations/0002_auto_20200911_1405.py
>>>>>>> Stashed changes
# Generated by Django 3.0 on 2020-09-11 17:05
=======
# Generated by Django 3.0 on 2020-09-23 18:40
>>>>>>> Stashed changes:apps/post/migrations/0002_auto_20200923_1540.py
<<<<<<< Updated upstream
=======
=======
# Generated by Django 3.0 on 2020-09-23 18:40
>>>>>>> Stashed changes:apps/post/migrations/0002_auto_20200923_1540.py
>>>>>>> Stashed changes
=======
<<<<<<< Updated upstream:apps/post/migrations/0003_auto_20200923_1610.py
# Generated by Django 3.0 on 2020-09-23 19:10
=======
# Generated by Django 3.0 on 2020-09-23 18:40
>>>>>>> Stashed changes:apps/post/migrations/0002_auto_20200923_1540.py
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

<<<<<<< Updated upstream
    initial = True

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
=======
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20200923_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
<<<<<<< Updated upstream:apps/post/migrations/0003_auto_20200923_1610.py
            old_name='usuario',
            new_name='usuario_comentario',
=======
>>>>>>> Stashed changes
            name='likes',
            field=models.ManyToManyField(related_name='likesPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsPost', to='post.Post'),
<<<<<<< Updated upstream
        ),
        migrations.AddField(
=======
>>>>>>> Stashed changes:apps/post/migrations/0002_auto_20200923_1540.py
        ),
        migrations.AlterField(
>>>>>>> Stashed changes
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
