# Generated by Django 3.0 on 2020-09-09 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
