# Generated by Django 3.0 on 2020-09-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200908_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='portada',
            field=models.ImageField(default='post/no-portada.jpg', upload_to='post/'),
        ),
    ]
