<<<<<<< Updated upstream
<<<<<<< Updated upstream:apps/post/migrations/0003_auto_20200923_1610.py
# Generated by Django 3.0 on 2020-09-23 19:10
=======
# Generated by Django 3.0 on 2020-09-23 18:40
>>>>>>> Stashed changes:apps/post/migrations/0002_auto_20200923_1540.py
=======
# Generated by Django 3.0 on 2020-09-23 19:10
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20200923_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
<<<<<<< Updated upstream
<<<<<<< Updated upstream:apps/post/migrations/0003_auto_20200923_1610.py
            old_name='usuario',
            new_name='usuario_comentario',
=======
            name='likes',
            field=models.ManyToManyField(related_name='likesPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsPost', to='post.Post'),
>>>>>>> Stashed changes:apps/post/migrations/0002_auto_20200923_1540.py
=======
            old_name='usuario',
            new_name='usuario_comentario',
>>>>>>> Stashed changes
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
<<<<<<< Updated upstream
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> Stashed changes
        ),
    ]
