# Generated by Django 3.0 on 2020-09-26 04:19

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200925_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='portada',
            field=models.ImageField(upload_to='post/', validators=[apps.post.models.validar_extension]),
        ),
    ]
