# Generated by Django 3.0 on 2020-09-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200923_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='usuario_comentario',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='usuario_comentario',
            new_name='usuario',
        ),
    ]
