# Generated by Django 3.0 on 2020-09-10 01:28

import apps.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='portada',
            field=models.ImageField(default='post/no-portada.jpg', upload_to='post/', validators=[apps.post.models.validar_extension]),
        ),
    ]
